export interface TriviaQuestion {
  q: string;
  choices: [string, string, string, string];
  correct: number;
  category: string;
}

export const QUESTIONS_PER_DAY = 8;

// Deliberately kept in English (matching the daily-word-puzzle pattern used by
// Word Ladder) — the question bank is content, not UI chrome. All surrounding
// UI text is fully translated instead.
export const QUESTIONS: TriviaQuestion[] = [
  { q: "What is the capital of Australia?", choices: ["Sydney", "Melbourne", "Canberra", "Perth"], correct: 2, category: "Geography" },
  { q: "Which planet is known as the Red Planet?", choices: ["Venus", "Mars", "Jupiter", "Saturn"], correct: 1, category: "Science" },
  { q: "Who wrote 'Romeo and Juliet'?", choices: ["Charles Dickens", "William Shakespeare", "Mark Twain", "Jane Austen"], correct: 1, category: "Literature" },
  { q: "What is the largest ocean on Earth?", choices: ["Atlantic", "Indian", "Arctic", "Pacific"], correct: 3, category: "Geography" },
  { q: "How many continents are there?", choices: ["5", "6", "7", "8"], correct: 2, category: "Geography" },
  { q: "What gas do plants absorb from the atmosphere?", choices: ["Oxygen", "Carbon Dioxide", "Nitrogen", "Hydrogen"], correct: 1, category: "Science" },
  { q: "Which country gifted the Statue of Liberty to the USA?", choices: ["France", "England", "Spain", "Italy"], correct: 0, category: "History" },
  { q: "What is the smallest prime number?", choices: ["0", "1", "2", "3"], correct: 2, category: "Math" },
  { q: "Which artist painted the Mona Lisa?", choices: ["Vincent van Gogh", "Pablo Picasso", "Leonardo da Vinci", "Claude Monet"], correct: 2, category: "Art" },
  { q: "What is the chemical symbol for gold?", choices: ["Go", "Gd", "Au", "Ag"], correct: 2, category: "Science" },
  { q: "How many players are on a standard soccer team on the field?", choices: ["9", "10", "11", "12"], correct: 2, category: "Sports" },
  { q: "Which is the longest river in the world?", choices: ["Amazon", "Nile", "Yangtze", "Mississippi"], correct: 1, category: "Geography" },
  { q: "In what year did World War II end?", choices: ["1943", "1944", "1945", "1946"], correct: 2, category: "History" },
  { q: "What is the hardest natural substance on Earth?", choices: ["Gold", "Iron", "Diamond", "Quartz"], correct: 2, category: "Science" },
  { q: "Which language has the most native speakers?", choices: ["English", "Hindi", "Spanish", "Mandarin Chinese"], correct: 3, category: "General" },
  { q: "What is the currency of Japan?", choices: ["Won", "Yuan", "Yen", "Ringgit"], correct: 2, category: "General" },
  { q: "Which organ pumps blood through the human body?", choices: ["Lungs", "Heart", "Liver", "Kidneys"], correct: 1, category: "Science" },
  { q: "What is the tallest mountain in the world?", choices: ["K2", "Kilimanjaro", "Everest", "Denali"], correct: 2, category: "Geography" },
  { q: "Which planet has the most moons?", choices: ["Earth", "Mars", "Jupiter", "Saturn"], correct: 3, category: "Science" },
  { q: "Who was the first person to walk on the Moon?", choices: ["Buzz Aldrin", "Yuri Gagarin", "Neil Armstrong", "John Glenn"], correct: 2, category: "History" },
  { q: "What is the main ingredient in guacamole?", choices: ["Tomato", "Avocado", "Onion", "Lime"], correct: 1, category: "Food" },
  { q: "How many strings does a standard guitar have?", choices: ["4", "5", "6", "7"], correct: 2, category: "Music" },
  { q: "Which country is home to the kangaroo?", choices: ["South Africa", "New Zealand", "Australia", "Brazil"], correct: 2, category: "Geography" },
  { q: "What does 'www' stand for?", choices: ["World Wide Web", "World Wild Web", "Web World Wide", "Wide World Web"], correct: 0, category: "Tech" },
  { q: "Which shape has three sides?", choices: ["Square", "Triangle", "Pentagon", "Hexagon"], correct: 1, category: "Math" },
  { q: "What is the freezing point of water in Celsius?", choices: ["-10", "0", "10", "32"], correct: 1, category: "Science" },
  { q: "Which country invented pizza as we know it today?", choices: ["Greece", "France", "Italy", "Spain"], correct: 2, category: "Food" },
  { q: "What is the largest mammal in the world?", choices: ["African Elephant", "Blue Whale", "Giraffe", "Polar Bear"], correct: 1, category: "Science" },
  { q: "Which country hosted the 2016 Summer Olympics?", choices: ["China", "UK", "Brazil", "Japan"], correct: 2, category: "Sports" },
  { q: "What is the capital of Canada?", choices: ["Toronto", "Vancouver", "Montreal", "Ottawa"], correct: 3, category: "Geography" },
  { q: "How many colors are in a rainbow?", choices: ["5", "6", "7", "8"], correct: 2, category: "General" },
  { q: "Which instrument has 88 keys?", choices: ["Organ", "Piano", "Harpsichord", "Accordion"], correct: 1, category: "Music" },
  { q: "What is the largest desert in the world?", choices: ["Sahara", "Gobi", "Antarctic", "Arabian"], correct: 2, category: "Geography" },
  { q: "Which vitamin is produced when skin is exposed to sunlight?", choices: ["Vitamin A", "Vitamin C", "Vitamin D", "Vitamin K"], correct: 2, category: "Science" },
  { q: "Who developed the theory of relativity?", choices: ["Isaac Newton", "Albert Einstein", "Niels Bohr", "Galileo Galilei"], correct: 1, category: "Science" },
  { q: "What is the national sport of Japan?", choices: ["Judo", "Karate", "Sumo wrestling", "Baseball"], correct: 2, category: "Sports" },
  { q: "Which ocean is the smallest?", choices: ["Indian", "Southern", "Arctic", "Atlantic"], correct: 2, category: "Geography" },
  { q: "What is the study of earthquakes called?", choices: ["Geology", "Seismology", "Meteorology", "Volcanology"], correct: 1, category: "Science" },
  { q: "Which country is famous for the Eiffel Tower?", choices: ["Italy", "Spain", "France", "Germany"], correct: 2, category: "Geography" },
  { q: "How many bones are in the adult human body?", choices: ["186", "206", "226", "246"], correct: 1, category: "Science" },
  { q: "Which sport is known as 'the beautiful game'?", choices: ["Basketball", "Tennis", "Soccer", "Cricket"], correct: 2, category: "Sports" },
  { q: "What is the largest country by land area?", choices: ["China", "USA", "Canada", "Russia"], correct: 3, category: "Geography" },
  { q: "Which fruit is known for keeping the doctor away?", choices: ["Banana", "Apple", "Orange", "Grape"], correct: 1, category: "Food" },
  { q: "What is H2O commonly known as?", choices: ["Salt", "Water", "Hydrogen peroxide", "Oxygen"], correct: 1, category: "Science" },
  { q: "Which continent is the Sahara Desert located in?", choices: ["Asia", "Africa", "South America", "Australia"], correct: 1, category: "Geography" },
  { q: "Who painted 'Starry Night'?", choices: ["Claude Monet", "Vincent van Gogh", "Salvador Dalí", "Pablo Picasso"], correct: 1, category: "Art" },
  { q: "What do bees produce?", choices: ["Silk", "Honey", "Wax only", "Milk"], correct: 1, category: "Science" },
  { q: "Which country is shaped like a boot?", choices: ["Greece", "Italy", "Spain", "Portugal"], correct: 1, category: "Geography" },
  { q: "How many hearts does an octopus have?", choices: ["1", "2", "3", "4"], correct: 2, category: "Science" },
  { q: "What is the tallest animal in the world?", choices: ["Elephant", "Giraffe", "Camel", "Ostrich"], correct: 1, category: "Science" },
  { q: "Which language is primarily spoken in Brazil?", choices: ["Spanish", "Portuguese", "French", "Italian"], correct: 1, category: "General" },
  { q: "What is the closest star to Earth?", choices: ["Proxima Centauri", "Sirius", "The Sun", "Polaris"], correct: 2, category: "Science" },
  { q: "Which sea creature has eight arms?", choices: ["Squid", "Octopus", "Jellyfish", "Starfish"], correct: 1, category: "Science" },
  { q: "What year did the Titanic sink?", choices: ["1905", "1912", "1918", "1923"], correct: 1, category: "History" },
  { q: "Which country is the birthplace of the Olympic Games?", choices: ["Italy", "Egypt", "Greece", "Turkey"], correct: 2, category: "History" },
  { q: "What is the main gas found in Earth's atmosphere?", choices: ["Oxygen", "Carbon Dioxide", "Nitrogen", "Hydrogen"], correct: 2, category: "Science" },
  { q: "Which animal is known as the King of the Jungle?", choices: ["Tiger", "Lion", "Elephant", "Gorilla"], correct: 1, category: "General" },
  { q: "What is the capital of Egypt?", choices: ["Alexandria", "Giza", "Cairo", "Luxor"], correct: 2, category: "Geography" },
  { q: "How many players are on a basketball team on the court?", choices: ["4", "5", "6", "7"], correct: 1, category: "Sports" },
  { q: "Which planet is closest to the sun?", choices: ["Venus", "Earth", "Mercury", "Mars"], correct: 2, category: "Science" },
  { q: "What is the largest organ in the human body?", choices: ["Liver", "Brain", "Skin", "Heart"], correct: 2, category: "Science" },
  { q: "Which country produces the most coffee?", choices: ["Colombia", "Vietnam", "Ethiopia", "Brazil"], correct: 3, category: "General" },
  { q: "What is the capital of Spain?", choices: ["Barcelona", "Madrid", "Seville", "Valencia"], correct: 1, category: "Geography" },
  { q: "Which metal is liquid at room temperature?", choices: ["Lead", "Mercury", "Tin", "Zinc"], correct: 1, category: "Science" },
  { q: "How many minutes are in a full day?", choices: ["1240", "1340", "1440", "1540"], correct: 2, category: "Math" },
  { q: "Which sport uses the term 'love' for zero points?", choices: ["Golf", "Tennis", "Cricket", "Badminton"], correct: 1, category: "Sports" },
  { q: "What is the world's largest coral reef system called?", choices: ["Red Sea Reef", "Great Barrier Reef", "Belize Reef", "Coral Triangle"], correct: 1, category: "Geography" },
  { q: "Which planet has the famous 'Great Red Spot'?", choices: ["Mars", "Saturn", "Jupiter", "Neptune"], correct: 2, category: "Science" },
  { q: "Who is known as the 'Father of Computers'?", choices: ["Alan Turing", "Charles Babbage", "Bill Gates", "Steve Jobs"], correct: 1, category: "Tech" },
  { q: "What is the most spoken official language in Africa?", choices: ["French", "Swahili", "Arabic", "English"], correct: 2, category: "General" },
  { q: "Which US state is known as the Sunshine State?", choices: ["California", "Florida", "Texas", "Arizona"], correct: 1, category: "Geography" },
  { q: "What is the square root of 64?", choices: ["6", "7", "8", "9"], correct: 2, category: "Math" },
  { q: "Which bird is famous for its inability to fly and lives in Antarctica?", choices: ["Ostrich", "Penguin", "Emu", "Kiwi"], correct: 1, category: "Science" },
  { q: "What is the name of Earth's only natural satellite?", choices: ["Titan", "The Moon", "Europa", "Phobos"], correct: 1, category: "Science" },
  { q: "Which country is famous for inventing sushi?", choices: ["China", "Korea", "Japan", "Thailand"], correct: 2, category: "Food" },
  { q: "How many sides does a hexagon have?", choices: ["5", "6", "7", "8"], correct: 1, category: "Math" },
  { q: "What is the tallest building in the world (as of the 2020s)?", choices: ["Shanghai Tower", "Burj Khalifa", "One World Trade Center", "Taipei 101"], correct: 1, category: "General" },
  { q: "Which gas do humans need to breathe to survive?", choices: ["Carbon Dioxide", "Nitrogen", "Oxygen", "Helium"], correct: 2, category: "Science" },
  { q: "What is the capital of Germany?", choices: ["Munich", "Hamburg", "Berlin", "Frankfurt"], correct: 2, category: "Geography" },
  { q: "Which sport is played at Wimbledon?", choices: ["Golf", "Tennis", "Cricket", "Rugby"], correct: 1, category: "Sports" },
  { q: "What is the process by which plants make food called?", choices: ["Respiration", "Photosynthesis", "Digestion", "Fermentation"], correct: 1, category: "Science" },
  { q: "Which continent has the most countries?", choices: ["Asia", "Europe", "Africa", "South America"], correct: 2, category: "Geography" },
  { q: "What is the largest planet in our solar system?", choices: ["Saturn", "Neptune", "Jupiter", "Uranus"], correct: 2, category: "Science" },
  { q: "Who wrote the novel '1984'?", choices: ["Aldous Huxley", "George Orwell", "Ray Bradbury", "H.G. Wells"], correct: 1, category: "Literature" },
  { q: "Which country is the birthplace of tea culture?", choices: ["India", "China", "Japan", "Sri Lanka"], correct: 1, category: "General" },
  { q: "How many teeth does an adult human typically have?", choices: ["28", "30", "32", "34"], correct: 2, category: "Science" },
  { q: "Which planet is known for its prominent ring system?", choices: ["Mars", "Saturn", "Jupiter", "Uranus"], correct: 1, category: "Science" },
  { q: "What is the world's most widely spoken second language?", choices: ["French", "Spanish", "English", "Mandarin"], correct: 2, category: "General" },
  { q: "Which country is home to the ancient city of Machu Picchu?", choices: ["Mexico", "Peru", "Chile", "Bolivia"], correct: 1, category: "Geography" },
  { q: "What is the boiling point of water at sea level in Celsius?", choices: ["90", "100", "110", "120"], correct: 1, category: "Science" },
  { q: "Which animal is the fastest land animal?", choices: ["Lion", "Gazelle", "Cheetah", "Horse"], correct: 2, category: "Science" },
  { q: "What is the name for a group of lions?", choices: ["Pack", "Herd", "Pride", "Flock"], correct: 2, category: "General" },
  { q: "Which country gave the world the game of chess?", choices: ["China", "India", "Persia", "Egypt"], correct: 1, category: "History" },
  { q: "What is the largest internal organ in the human body?", choices: ["Kidney", "Liver", "Lungs", "Stomach"], correct: 1, category: "Science" },
  { q: "Which planet is often called Earth's twin due to similar size?", choices: ["Mars", "Venus", "Mercury", "Neptune"], correct: 1, category: "Science" },
  { q: "What is the currency used in most of the European Union?", choices: ["Franc", "Euro", "Mark", "Pound"], correct: 1, category: "General" },
  { q: "Which sport is associated with the term 'hat-trick'?", choices: ["Basketball", "Soccer", "Volleyball", "Tennis"], correct: 1, category: "Sports" },
  { q: "What do you call baby dogs?", choices: ["Kittens", "Puppies", "Cubs", "Kids"], correct: 1, category: "General" },
  { q: "Which country is famous for the Great Wall?", choices: ["Japan", "Mongolia", "China", "Korea"], correct: 2, category: "History" },
  { q: "What is the chemical symbol for water?", choices: ["H2O", "O2", "CO2", "H2O2"], correct: 0, category: "Science" },
  { q: "Which continent is the smallest by land area?", choices: ["Europe", "Antarctica", "Australia", "South America"], correct: 2, category: "Geography" },
  { q: "How many players are on a volleyball team on the court?", choices: ["5", "6", "7", "8"], correct: 1, category: "Sports" },
  { q: "What is the name of the galaxy that contains our solar system?", choices: ["Andromeda", "Milky Way", "Whirlpool", "Triangulum"], correct: 1, category: "Science" },
  { q: "Which fruit is a natural source of vitamin C famously linked to preventing scurvy?", choices: ["Banana", "Orange", "Grape", "Pear"], correct: 1, category: "Food" },
  { q: "What is the term for a word that reads the same backward as forward?", choices: ["Synonym", "Palindrome", "Acronym", "Homophone"], correct: 1, category: "General" },
  { q: "Which country has the most natural lakes?", choices: ["USA", "Russia", "Canada", "Finland"], correct: 2, category: "Geography" },
  { q: "What is the powerhouse of the cell called?", choices: ["Nucleus", "Ribosome", "Mitochondria", "Cytoplasm"], correct: 2, category: "Science" },
  { q: "Which of these is not a primary color?", choices: ["Red", "Green", "Blue", "Yellow"], correct: 1, category: "Art" },
  { q: "What is the name of the first artificial satellite launched into space?", choices: ["Apollo 11", "Sputnik 1", "Voyager 1", "Explorer 1"], correct: 1, category: "History" },
  { q: "Which country is known as the Land of the Rising Sun?", choices: ["China", "South Korea", "Japan", "Thailand"], correct: 2, category: "General" },
  { q: "What is the standard number of squares on a chessboard?", choices: ["32", "48", "64", "100"], correct: 2, category: "General" },
  { q: "Which part of the plant conducts photosynthesis?", choices: ["Root", "Stem", "Leaf", "Flower"], correct: 2, category: "Science" },
  { q: "What is the capital city of the United Kingdom?", choices: ["Manchester", "Liverpool", "London", "Birmingham"], correct: 2, category: "Geography" },
  { q: "Which of these animals is a marsupial?", choices: ["Koala", "Panda", "Raccoon", "Otter"], correct: 0, category: "Science" },
  { q: "What do you call a shape with 5 sides?", choices: ["Hexagon", "Pentagon", "Heptagon", "Octagon"], correct: 1, category: "Math" },
  { q: "Which explorer is credited with reaching the Americas in 1492?", choices: ["Magellan", "Columbus", "Vasco da Gama", "Cortés"], correct: 1, category: "History" },
  { q: "What is the primary language spoken in Egypt?", choices: ["Arabic", "French", "Hebrew", "Turkish"], correct: 0, category: "General" },
  { q: "Which gas makes up the majority of the air we exhale?", choices: ["Oxygen", "Nitrogen", "Carbon Dioxide", "Hydrogen"], correct: 1, category: "Science" },
  { q: "What is the name for the imaginary line dividing Earth into Northern and Southern Hemispheres?", choices: ["Prime Meridian", "Equator", "Tropic of Cancer", "International Date Line"], correct: 1, category: "Geography" },
  { q: "Which sport originated in Scotland?", choices: ["Tennis", "Golf", "Rugby", "Boxing"], correct: 1, category: "Sports" },
  { q: "What is the name of the fairy tale character who lost a glass slipper?", choices: ["Snow White", "Cinderella", "Rapunzel", "Belle"], correct: 1, category: "General" },
  { q: "Which of these is the largest species of big cat?", choices: ["Lion", "Tiger", "Jaguar", "Leopard"], correct: 1, category: "Science" },
  { q: "What do you call the study of stars and planets?", choices: ["Biology", "Astronomy", "Geology", "Chemistry"], correct: 1, category: "Science" },
  { q: "Which country was the first to give women the right to vote?", choices: ["USA", "France", "New Zealand", "UK"], correct: 2, category: "History" },
];
